chore: "Changed all go functions to use the new API"
memphisdev/memphis-dev-functions pull request #12
Opened 2023-12-14 04:36 UTC by John-Memphis

2023-12-14 08:31 UTC, shay23b requested changes

2023-12-14 08:31 UTC, shay23b commented on add-geolocation/main.go
> +	as_byes := message.([]byte)
as_byes -> as_bytes

2023-12-14 08:31 UTC, shay23b commented on add-geolocation/main.go
> +	if err := json.Unmarshal(as_byes, &event); err != nil{
as_byes -> as_bytes

2023-12-31 09:15 UTC, idanasulinmemphis commented
memphis-functions.go has been released with version 2.0.0 so please update the relevant go.mod/sum files to use the new version and make last check everything is working

2024-01-15 10:03 UTC, shay23b approved these changes

2024-01-15 14:45 UTC, merged